### ISSUE TITLE
restore copyrights

### ISSUE THREAD

**Issue by totaam** [andersevenrud/xpra-html5-client#1]
Please restore the license and copyright notice on all the files you modified.

Changing the code structure and language does not allow you to remove the copyright notice, or change the license.

**Comment by andersevenrud** [comment]
I've added the copyright preambles to all files.

Let me know if there's a LICENSE file I also need to include or anything

**Comment by totaam** [comment]
Thanks. Feel free to close this ticket.
We don't include the license file directly ourselves (maybe we should?).

**Comment by andersevenrud** [comment]
I was looking for one when I created this repo but didn't find any, which is why I linked the original repo in all headers and such.

It's probably a good idea. I now realize that I've forgotten to commit the one for this repo :man_facepalming:

**Comment by totaam** [comment]
> It's probably a good idea.

Agreed:
http://xpra.org/trac/changeset/21791

**Comment by andersevenrud** [comment]
Nice!

I added a copy of it in this repo: https://github.com/andersevenrud/xpra-html5-client/blob/master/LICENSE.xpra

**Comment by andersevenrud** [comment]
README now reflects this as well.
