### ISSUE TITLE
Interface stuck after connecting

### ISSUE THREAD

**Issue by oeway** [andersevenrud/xpra-html5-client#2]
Hi, thanks for sharing the library. I just tried with the latest version of xpra but cannot get it to work. It said connected and I do see the window populated, however, I cannot interact with the window normally. With the official html client I can use it normally.

**Comment by andersevenrud** [comment]
>  I do see the window populated, however, I cannot interact with the window normally

Sounds like either:

1. Events are not triggered
2. Something changed in the xpra protocol and this library needs an update

**Comment by andersevenrud** [comment]
Closing this because I've deprecated the 1.x version of this library.
