### ISSUE TITLE
xpra-html5-client dependencies not published

### ISSUE THREAD

**Issue by shmuelhizmi** [andersevenrud/xpra-html5-client#5]
hey, I'm trying to install xpra-html5-client and I get the error
```Couldn't find package "xpra-av@^1.0.0" required by "xpra-html5-client@2.2.0" on the "npm" registry.```
this is because you didn't yet publish xpra-html5-client's dependencies from your mono-repo

**Comment by andersevenrud** [comment]
Ah, yes. I haven't actually tested this myself yet in a standalone project. I''m bundling xpra-av and the other deps in the physical bundle, so I need to change the dependencies list in the published package.

**Comment by andersevenrud** [comment]
I'll fix this today and give you a ping when you can test again.

**Comment by andersevenrud** [comment]
Pretty sure this has been fixed, so I'll close this issue. If you still get some problems, feel free to re-open.

Thanks for letting me know about this!

**Comment by shmuelhizmi** [comment]
Thanks!
